from pynput.keyboard import Key, Controller as KeyboardController
from pynput.mouse import Button, Controller as MouseController
import pyperclip
import time

keyboard = KeyboardController()
mouse = MouseController()

def tabPress(qtd):
	for x in range(qtd):
		keyboard.press(Key.tab)
		keyboard.release(Key.tab)
		time.sleep(1)


# URL PROXY: https://www.kproxy.com
def getChrome(url):
	urlProxy = 'https://www.kproxy.com'

	mouse.position = (1243,509) #Click null area
	mouse.click(Button.left, 1)
	time.sleep(1)

	keyboard.press(Key.f6) #Chrome command to access link navigation
	keyboard.release(Key.f6)
	time.sleep(1)

	keyboard.type(urlProxy) #Type url proxy site

	keyboard.press(Key.enter) #Enter to access proxy site
	keyboard.release(Key.enter)
	time.sleep(5)

	tabPress(8) #Tab Key to type url in kproxy.com

	keyboard.type(url) #Type URL media in proxy site
	time.sleep(1)
	
	tabPress(1) #Access link to go URL media
	time.sleep(1)

	keyboard.press(Key.space) # Press to access URL media
	keyboard.release(Key.space)
	time.sleep(4)

	keyboard.press(Key.f6) #Chrome command to access link navigation
	keyboard.release(Key.f6)
	time.sleep(1)

	keyboard.press(Key.ctrl) #Copy URL generated by kproxy
	keyboard.press('c')
	keyboard.release('c')
	keyboard.release(Key.ctrl)
	getURL = pyperclip.paste()

	if 'invalid' not in getURL:
		return getURL

	getChrome(url)
def chromeURL(url):  
	time.sleep(2)
	mouse.position = (206,884) #Open Chrome
	mouse.click(Button.left, 1)
	time.sleep(7)
	urlSessionOk = getChrome(url)	
	return urlSessionOk

def getFirefox(url):
	urlProxy = 'https://www.kproxy.com'
	mouse.position = (1243,509) #Click null area
	mouse.click(Button.left, 1)
	time.sleep(1)

	keyboard.press(Key.f6) #Firefox command to access link navigation
	keyboard.release(Key.f6)
	time.sleep(1)

	keyboard.type(urlProxy) #Type url proxy site

	keyboard.press(Key.enter) #Enter to access proxy site
	keyboard.release(Key.enter)
	time.sleep(5)

	tabPress(8) #Tab Key to type url in kproxy.com

	keyboard.type(url) #Type URL media in proxy site
	time.sleep(1)
	
	tabPress(1) #Access link to go URL media
	time.sleep(1)

	keyboard.press(Key.space) # Press to access URL media
	keyboard.release(Key.space)
	time.sleep(4)

	keyboard.press(Key.f6) #Firefox command to access link navigation
	keyboard.release(Key.f6)
	time.sleep(1)

	keyboard.press(Key.ctrl) #Copy URL generated by kproxy
	keyboard.press('c')
	keyboard.release('c')
	keyboard.release(Key.ctrl)
	getURL = pyperclip.paste()

	if 'invalid' not in getURL:
		return getURL

	getFirefox(url)
def firefoxURL(url):  	
	time.sleep(2)
	mouse.position = (175,885) #Open Firefox before loop
	mouse.click(Button.left, 1)
	time.sleep(7)	
	urlSessionOk = getFirefox(url)	
	return urlSessionOk

def getFalkon(url):
	urlProxy = 'https://www.kproxy.com'
	mouse.position = (1243,509) #Click null area
	mouse.click(Button.left, 1)
	time.sleep(1)

	keyboard.press(Key.f6) #Falkon command to access link navigation
	keyboard.release(Key.f6)
	time.sleep(1)

	keyboard.type(urlProxy) #Type url proxy site

	keyboard.press(Key.enter) #Enter to access proxy site
	keyboard.release(Key.enter)
	time.sleep(5)

	tabPress(1) #Tab Key to type url in kproxy.com

	keyboard.type(url) #Type URL media in proxy site
	time.sleep(1)
	
	tabPress(1) #Access link to go URL media
	time.sleep(1)

	keyboard.press(Key.space) # Press to access URL media
	keyboard.release(Key.space)
	time.sleep(4)

	keyboard.press(Key.f6) #Falkon command to access link navigation
	keyboard.release(Key.f6)
	time.sleep(1)

	keyboard.press(Key.ctrl) #Copy URL generated by kproxy
	keyboard.press('c')
	keyboard.release('c')
	keyboard.release(Key.ctrl)
	getURL = pyperclip.paste()

	if 'invalid' not in getURL:
		return getURL

	getFalkon(url)
def falkonURL(url):  	
	time.sleep(2)
	mouse.position = (236,885) #Open Falkon 
	mouse.click(Button.left, 1)
	time.sleep(7)
	urlSessionOk = getFalkon(url)	
	return urlSessionOk

def getGnome(url):
	urlProxy = 'https://www.kproxy.com'
	mouse.position = (1243,509) #Click null area
	mouse.click(Button.left, 1)
	time.sleep(1)

	keyboard.press(Key.f6) #Gnome command to access link navigation
	keyboard.release(Key.f6)
	time.sleep(1)

	keyboard.type(urlProxy) #Type url proxy site

	keyboard.press(Key.enter) #Enter to access proxy site
	keyboard.release(Key.enter)
	time.sleep(5)

	tabPress(8) #Tab Key to type url in kproxy.com

	keyboard.type(url) #Type URL media in proxy site
	time.sleep(1)
	
	tabPress(1) #Access link to go URL media
	time.sleep(1)

	keyboard.press(Key.space) # Press to access URL media
	keyboard.release(Key.space)
	time.sleep(4)

	keyboard.press(Key.f6) #Gnome command to access link navigation
	keyboard.release(Key.f6)
	time.sleep(1)

	keyboard.press(Key.ctrl) #Copy URL generated by kproxy
	keyboard.press('c')
	keyboard.release('c')
	keyboard.release(Key.ctrl)
	getURL = pyperclip.paste()

	if 'invalid' not in getURL:
		return getURL

	getGnome(url)
def gnomeURL(url):  
	time.sleep(2)
	mouse.position = (267,885) #Open Gnome before loop
	mouse.click(Button.left, 1)
	time.sleep(7)
	urlSessionOk = getGnome(url)	
	return urlSessionOk

def getPalemoon(url):
	urlProxy = 'https://www.kproxy.com'
	mouse.position = (1243,509) #Click null area
	mouse.click(Button.left, 1)
	time.sleep(1)

	keyboard.press(Key.f6) #Gnome command to access link navigation
	keyboard.release(Key.f6)
	time.sleep(1)

	keyboard.type(urlProxy) #Type url proxy site

	keyboard.press(Key.enter) #Enter to access proxy site
	keyboard.release(Key.enter)
	time.sleep(5)

	tabPress(8) #Tab Key to type url in kproxy.com

	keyboard.type(url) #Type URL media in proxy site
	time.sleep(1)
	
	tabPress(1) #Access link to go URL media
	time.sleep(1)

	keyboard.press(Key.space) # Press to access URL media
	keyboard.release(Key.space)
	time.sleep(4)

	keyboard.press(Key.f6) #Gnome command to access link navigation
	keyboard.release(Key.f6)
	time.sleep(1)

	keyboard.press(Key.ctrl) #Copy URL generated by kproxy
	keyboard.press('c')
	keyboard.release('c')
	keyboard.release(Key.ctrl)
	getURL = pyperclip.paste()

	if 'invalid' not in getURL:
		return getURL

	getPalemoon(url)
def palemoonURL(url): 
	time.sleep(2)
	mouse.position = (297,886) #Open Palemoon before loop
	mouse.click(Button.left, 1)
	time.sleep(7)	
	urlSessionOk = getPalemoon(url)	
	return urlSessionOk
	
def getYandex(url):
	urlProxy = 'https://www.kproxy.com'

	keyboard.type(urlProxy) #Type url proxy site

	keyboard.press(Key.enter) #Enter to access proxy site
	keyboard.release(Key.enter)
	time.sleep(5)

	tabPress(8) #Tab Key to type url in kproxy.com

	keyboard.type(url) #Type URL media in proxy site
	time.sleep(1)
	
	tabPress(1) #Access link to go URL media
	time.sleep(1)

	keyboard.press(Key.space) # Press to access URL media
	keyboard.release(Key.space)
	time.sleep(4)

	keyboard.press(Key.f6) #Gnome command to access link navigation
	keyboard.release(Key.f6)
	time.sleep(1)

	keyboard.press(Key.ctrl) #Copy URL generated by kproxy
	keyboard.press('c')
	keyboard.release('c')
	keyboard.release(Key.ctrl)
	getURL = pyperclip.paste()

	if 'invalid' not in getURL:
		return getURL

	keyboard.press(Key.f6) #Gnome command to access link navigation
	keyboard.release(Key.f6)
	time.sleep(1)
	getYandex(url)
def yandexURL(url):  	
	time.sleep(2)
	mouse.position = (329,886) #Open Yandex 
	mouse.click(Button.left, 1)
	time.sleep(7)
	urlSessionOk = getYandex(url)	
	return urlSessionOk

def getSlimjet(url):
	urlProxy = 'https://www.kproxy.com'

	mouse.position = (1243,509) #Click null area
	mouse.click(Button.left, 1)
	time.sleep(1)

	keyboard.press(Key.f6) #Chrome command to access link navigation
	keyboard.release(Key.f6)
	time.sleep(1)

	keyboard.type(urlProxy) #Type url proxy site

	keyboard.press(Key.enter) #Enter to access proxy site
	keyboard.release(Key.enter)
	time.sleep(5)

	tabPress(8) #Tab Key to type url in kproxy.com

	keyboard.type(url) #Type URL media in proxy site
	time.sleep(1)
	
	tabPress(1) #Access link to go URL media
	time.sleep(1)

	keyboard.press(Key.space) # Press to access URL media
	keyboard.release(Key.space)
	time.sleep(4)

	keyboard.press(Key.f6) #Chrome command to access link navigation
	keyboard.release(Key.f6)
	time.sleep(1)

	keyboard.press(Key.ctrl) #Copy URL generated by kproxy
	keyboard.press('c')
	keyboard.release('c')
	keyboard.release(Key.ctrl)
	getURL = pyperclip.paste()

	if 'invalid' not in getURL:
		return getURL

	getSlimjet(url)
def slimjetURL(url):
	time.sleep(2)
	mouse.position = (359,886) #Open Yandex before loop
	mouse.click(Button.left, 1)
	time.sleep(7)
	urlSessionOk = getSlimjet(url)	
	return urlSessionOk

def getWhaterfox(url):
	urlProxy = 'https://www.kproxy.com'
	mouse.position = (1243,509) #Click null area
	mouse.click(Button.left, 1)
	time.sleep(1)

	keyboard.press(Key.f6) #Firefox command to access link navigation
	keyboard.release(Key.f6)
	time.sleep(1)

	keyboard.type(urlProxy) #Type url proxy site

	keyboard.press(Key.enter) #Enter to access proxy site
	keyboard.release(Key.enter)
	time.sleep(5)

	tabPress(8) #Tab Key to type url in kproxy.com

	keyboard.type(url) #Type URL media in proxy site
	time.sleep(1)
	
	tabPress(1) #Access link to go URL media
	time.sleep(1)

	keyboard.press(Key.space) # Press to access URL media
	keyboard.release(Key.space)
	time.sleep(4)

	keyboard.press(Key.f6) #Firefox command to access link navigation
	keyboard.release(Key.f6)
	time.sleep(1)

	keyboard.press(Key.ctrl) #Copy URL generated by kproxy
	keyboard.press('c')
	keyboard.release('c')
	keyboard.release(Key.ctrl)
	getURL = pyperclip.paste()

	if 'invalid' not in getURL:
		return getURL

	getWhaterfox(url)
def whaterfoxURL(url):  	
	time.sleep(2)
	mouse.position = (392,885) #Open Firefox before loop
	mouse.click(Button.left, 1)
	time.sleep(7)	
	urlSessionOk = getWhaterfox(url)	
	return urlSessionOk