from pynput.keyboard import Key, Controller as KeyboardController
from pynput.mouse import Button, Controller as MouseController
import pyperclip
import time

keyboard = KeyboardController()
mouse = MouseController()

def tabPress(qtd):
	for x in range(qtd):
		keyboard.press(Key.tab)
		keyboard.release(Key.tab)
		time.sleep(1)


# chrome FOTO: 3TAB || VIDEO: 6TAB
# URL PROXY: https://www.kproxy.com
def chrome(url, mediaTabTimes):  

	urlProxy = 'https://www.kproxy.com'
	time.sleep(2)
	mouse.position = (206,884) #Open Chrome
	mouse.click(Button.left, 1)
	time.sleep(7)

	mouse.position = (1243,509) #Click null area
	mouse.click(Button.left, 1)
	time.sleep(1)

	keyboard.press(Key.f6) #Chrome command to access link navigation
	keyboard.release(Key.f6)
	time.sleep(1)

	keyboard.type(urlProxy) #Type url proxy site

	keyboard.press(Key.enter) #Enter to access proxy site
	keyboard.release(Key.enter)
	time.sleep(7)

	tabPress(8) #Tab Key to type url in kproxy.com

	keyboard.type(url) #Type URL media in proxy site
	time.sleep(1)
	
	tabPress(1) #Access link to go URL media
	time.sleep(1)

	keyboard.press(Key.space) # Press to access URL media
	keyboard.release(Key.space)
	time.sleep(7)

	keyboard.press(Key.f6) #Chrome command to access link navigation
	keyboard.release(Key.f6)
	time.sleep(1)

	keyboard.press(Key.ctrl) #Copy URL generated by kproxy
	keyboard.press('c')
	keyboard.release('c')
	keyboard.release(Key.ctrl)
	getURL = pyperclip.paste()

	count = 1
	for x in range(9):
		arrayURL = getURL.splice('.kproxy')
		print('Nova ordem recebida - {}'.format(ordemRecebida['coin']))	
		urlToLike = 'server{}.kproxy{}'.format(count, arrayURL[1])
		count = count + 1


def like(url):
	keyboard.press(Key.f6) #Chrome command to access link navigation
	keyboard.release(Key.f6)
	time.sleep(1)

	keyboard.type(url) #Type url proxy site

	keyboard.press(Key.enter) #Enter to access proxy site
	keyboard.release(Key.enter)
	time.sleep(7)

	mouse.position = (718,488) #Modal
	mouse.click(Button.left, 1)
	time.sleep(3)

	mouse.position = (1281,378) #Click null area
	mouse.click(Button.left, 1)
	time.sleep(1)

	tabPress(mediaTabTimes) #Tab Key

	keyboard.press(Key.space)
	keyboard.release(Key.space)
	time.sleep(3)

	#mouse.position = (1422,17) #Close browser
	#mouse.click(Button.left, 1)



def startRequest(url,mediaTabTimes):
  qtdTabByMediaType = 0
  if mediaTabTimes == 'foto':
    qtdTabByMediaType = 3
  if mediaTabTimes == 'video':
    qtdTabByMediaType = 6
  if qtdTabByMediaType == 0:
    return

  chrome(url,qtdTabByMediaType,eua1X,eua1Y)
  chrome(url,qtdTabByMediaType,eua2X,eua2Y)
  chrome(url,qtdTabByMediaType,aleX,aleY)
  chrome(url,qtdTabByMediaType,holX,holY)
  chrome(url,qtdTabByMediaType,ruX,ruY)
  chrome(url,qtdTabByMediaType,repX,repY)

